name: Deploy Go Application to CentOS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          go mod tidy

      # Step 4: Build the application
      - name: Build the application
        run: |
          go build -o tesla_server main.go

      # Step 5: Deploy to CentOS server
      - name: Deploy and restart service on CentOS
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Write private key to a file
          echo "${SSH_PRIVATE_KEY}" > private_key
          chmod 600 private_key
      
          # Copy the built executable to the server
          scp -i private_key -o StrictHostKeyChecking=no tesla_server $SERVER_USER@$SERVER_IP:/tmp/tesla_server
      
          # Run commands on the CentOS server
          ssh -i private_key -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << EOF
            # Create the systemd service file if it doesn't exist
            if [ ! -f /etc/systemd/system/tesla_server.service ]; then
              echo "[Unit]
              Description=Tesla Server
              After=network.target
      
              [Service]
              ExecStart=/usr/local/bin/tesla_server
              WorkingDirectory=/home/ec2-user/tesla_server
              User=ec2-user
              Group=ec2-user
              Restart=always
      
              [Install]
              WantedBy=multi-user.target" | sudo tee /etc/systemd/system/tesla_server.service
              sudo systemctl daemon-reload
            fi
      
            # Stop the service if it exists
            if systemctl list-units --type=service | grep -q "tesla_server.service"; then
              sudo systemctl stop tesla_server
            fi
      
            # Move the new executable and set permissions
            sudo mv /tmp/tesla_server /usr/local/bin/tesla_server
            sudo chmod +x /usr/local/bin/tesla_server
      
            # Reload systemd, start and enable the service
            sudo systemctl daemon-reload
            sudo systemctl start tesla_server
            sudo systemctl enable tesla_server
          EOF
      
          # Clean up the private key
          rm private_key
